PKG_NAME = "pepdbagent"

DEFAULT_NAMESPACE = "_"
DEFAULT_TAG = "default"

DESCRIPTION_KEY = "description"
NAME_KEY = "name"

# from peppy.const import SAMPLE_RAW_DICT_KEY, SUBSAMPLE_RAW_LIST_KEY

DEFAULT_OFFSET = 0
DEFAULT_LIMIT = 100

# db_dialects
POSTGRES_DIALECT = "postgresql+psycopg"

DEFAULT_LIMIT_INFO = 5

SUBMISSION_DATE_KEY = "submission_date"
LAST_UPDATE_DATE_KEY = "last_update_date"

PEPHUB_SAMPLE_ID_KEY = "ph_id"

MAX_HISTORY_SAMPLES_NUMBER = 2000

DEFAULT_TAG_VERSION = "1.0.0"
LATEST_SCHEMA_VERSION = "latest"
